// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: mtd.proto

package mtd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadInfoResponse_TaskStatus int32

const (
	DownloadInfoResponse_QUEUED     DownloadInfoResponse_TaskStatus = 0
	DownloadInfoResponse_INPROGRESS DownloadInfoResponse_TaskStatus = 1
	DownloadInfoResponse_PAUSED     DownloadInfoResponse_TaskStatus = 2
	DownloadInfoResponse_COMPLETED  DownloadInfoResponse_TaskStatus = 3
	DownloadInfoResponse_ERRORED    DownloadInfoResponse_TaskStatus = 4
)

// Enum value maps for DownloadInfoResponse_TaskStatus.
var (
	DownloadInfoResponse_TaskStatus_name = map[int32]string{
		0: "QUEUED",
		1: "INPROGRESS",
		2: "PAUSED",
		3: "COMPLETED",
		4: "ERRORED",
	}
	DownloadInfoResponse_TaskStatus_value = map[string]int32{
		"QUEUED":     0,
		"INPROGRESS": 1,
		"PAUSED":     2,
		"COMPLETED":  3,
		"ERRORED":    4,
	}
)

func (x DownloadInfoResponse_TaskStatus) Enum() *DownloadInfoResponse_TaskStatus {
	p := new(DownloadInfoResponse_TaskStatus)
	*p = x
	return p
}

func (x DownloadInfoResponse_TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownloadInfoResponse_TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mtd_proto_enumTypes[0].Descriptor()
}

func (DownloadInfoResponse_TaskStatus) Type() protoreflect.EnumType {
	return &file_mtd_proto_enumTypes[0]
}

func (x DownloadInfoResponse_TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownloadInfoResponse_TaskStatus.Descriptor instead.
func (DownloadInfoResponse_TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_mtd_proto_rawDescGZIP(), []int{3, 0}
}

type HTTPDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL      string                        `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
	Chunks   uint32                        `protobuf:"varint,2,opt,name=Chunks,proto3" json:"Chunks,omitempty"`
	BufSize  int64                         `protobuf:"varint,3,opt,name=BufSize,proto3" json:"BufSize,omitempty"`
	Headers  []*HTTPDownloadRequest_Header `protobuf:"bytes,4,rep,name=Headers,proto3" json:"Headers,omitempty"`
	FilePath string                        `protobuf:"bytes,5,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
}

func (x *HTTPDownloadRequest) Reset() {
	*x = HTTPDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPDownloadRequest) ProtoMessage() {}

func (x *HTTPDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPDownloadRequest.ProtoReflect.Descriptor instead.
func (*HTTPDownloadRequest) Descriptor() ([]byte, []int) {
	return file_mtd_proto_rawDescGZIP(), []int{0}
}

func (x *HTTPDownloadRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *HTTPDownloadRequest) GetChunks() uint32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *HTTPDownloadRequest) GetBufSize() int64 {
	if x != nil {
		return x.BufSize
	}
	return 0
}

func (x *HTTPDownloadRequest) GetHeaders() []*HTTPDownloadRequest_Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPDownloadRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type HTTPDownloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *HTTPDownloadResponse) Reset() {
	*x = HTTPDownloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPDownloadResponse) ProtoMessage() {}

func (x *HTTPDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPDownloadResponse.ProtoReflect.Descriptor instead.
func (*HTTPDownloadResponse) Descriptor() ([]byte, []int) {
	return file_mtd_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPDownloadResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DownloadInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *DownloadInfoRequest) Reset() {
	*x = DownloadInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadInfoRequest) ProtoMessage() {}

func (x *DownloadInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mtd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadInfoRequest.ProtoReflect.Descriptor instead.
func (*DownloadInfoRequest) Descriptor() ([]byte, []int) {
	return file_mtd_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadInfoRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type DownloadInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status DownloadInfoResponse_TaskStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=mtd.DownloadInfoResponse_TaskStatus" json:"Status,omitempty"`
	// Total content length in bytes
	ContentLength int64 `protobuf:"varint,2,opt,name=ContentLength,proto3" json:"ContentLength,omitempty"`
	// Elapsed time in seconds
	Elapsed int64 `protobuf:"varint,3,opt,name=Elapsed,proto3" json:"Elapsed,omitempty"`
}

func (x *DownloadInfoResponse) Reset() {
	*x = DownloadInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadInfoResponse) ProtoMessage() {}

func (x *DownloadInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mtd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadInfoResponse.ProtoReflect.Descriptor instead.
func (*DownloadInfoResponse) Descriptor() ([]byte, []int) {
	return file_mtd_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadInfoResponse) GetStatus() DownloadInfoResponse_TaskStatus {
	if x != nil {
		return x.Status
	}
	return DownloadInfoResponse_QUEUED
}

func (x *DownloadInfoResponse) GetContentLength() int64 {
	if x != nil {
		return x.ContentLength
	}
	return 0
}

func (x *DownloadInfoResponse) GetElapsed() int64 {
	if x != nil {
		return x.Elapsed
	}
	return 0
}

type HTTPDownloadRequest_Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *HTTPDownloadRequest_Header) Reset() {
	*x = HTTPDownloadRequest_Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mtd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPDownloadRequest_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPDownloadRequest_Header) ProtoMessage() {}

func (x *HTTPDownloadRequest_Header) ProtoReflect() protoreflect.Message {
	mi := &file_mtd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPDownloadRequest_Header.ProtoReflect.Descriptor instead.
func (*HTTPDownloadRequest_Header) Descriptor() ([]byte, []int) {
	return file_mtd_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HTTPDownloadRequest_Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HTTPDownloadRequest_Header) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

var File_mtd_proto protoreflect.FileDescriptor

var file_mtd_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x74, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x74, 0x64,
	0x22, 0xde, 0x01, 0x0a, 0x13, 0x48, 0x54, 0x54, 0x50, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x75, 0x66, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x75, 0x66, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x39, 0x0a, 0x07,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x6d, 0x74, 0x64, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x07,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x50,
	0x61, 0x74, 0x68, 0x1a, 0x2c, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61,
	0x6c, 0x22, 0x26, 0x0a, 0x14, 0x48, 0x54, 0x54, 0x50, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0xe6, 0x01, 0x0a, 0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6d, 0x74, 0x64, 0x2e,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x18, 0x0a,
	0x07, 0x45, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x45, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x22, 0x50, 0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e, 0x50, 0x52, 0x4f, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x41, 0x55, 0x53, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x45, 0x44, 0x10, 0x04, 0x32, 0x9d, 0x01, 0x0a, 0x03, 0x6d, 0x74,
	0x64, 0x12, 0x4a, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x54, 0x54, 0x50,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x2e, 0x6d, 0x74, 0x64, 0x2e, 0x48,
	0x54, 0x54, 0x50, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6d, 0x74, 0x64, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a,
	0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x2e, 0x6d, 0x74, 0x64, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x6d, 0x74, 0x64, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x75, 0x73, 0x73, 0x65, 0x69, 0x6e, 0x65,
	0x6c, 0x67, 0x75, 0x69, 0x6e, 0x64, 0x69, 0x2f, 0x6d, 0x74, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x6d, 0x74, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mtd_proto_rawDescOnce sync.Once
	file_mtd_proto_rawDescData = file_mtd_proto_rawDesc
)

func file_mtd_proto_rawDescGZIP() []byte {
	file_mtd_proto_rawDescOnce.Do(func() {
		file_mtd_proto_rawDescData = protoimpl.X.CompressGZIP(file_mtd_proto_rawDescData)
	})
	return file_mtd_proto_rawDescData
}

var file_mtd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mtd_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mtd_proto_goTypes = []interface{}{
	(DownloadInfoResponse_TaskStatus)(0), // 0: mtd.DownloadInfoResponse.TaskStatus
	(*HTTPDownloadRequest)(nil),          // 1: mtd.HTTPDownloadRequest
	(*HTTPDownloadResponse)(nil),         // 2: mtd.HTTPDownloadResponse
	(*DownloadInfoRequest)(nil),          // 3: mtd.DownloadInfoRequest
	(*DownloadInfoResponse)(nil),         // 4: mtd.DownloadInfoResponse
	(*HTTPDownloadRequest_Header)(nil),   // 5: mtd.HTTPDownloadRequest.Header
}
var file_mtd_proto_depIdxs = []int32{
	5, // 0: mtd.HTTPDownloadRequest.Headers:type_name -> mtd.HTTPDownloadRequest.Header
	0, // 1: mtd.DownloadInfoResponse.Status:type_name -> mtd.DownloadInfoResponse.TaskStatus
	1, // 2: mtd.mtd.RequestHTTPDownload:input_type -> mtd.HTTPDownloadRequest
	3, // 3: mtd.mtd.RequestDownloadInfo:input_type -> mtd.DownloadInfoRequest
	2, // 4: mtd.mtd.RequestHTTPDownload:output_type -> mtd.HTTPDownloadResponse
	4, // 5: mtd.mtd.RequestDownloadInfo:output_type -> mtd.DownloadInfoResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mtd_proto_init() }
func file_mtd_proto_init() {
	if File_mtd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mtd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPDownloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mtd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTTPDownloadRequest_Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mtd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mtd_proto_goTypes,
		DependencyIndexes: file_mtd_proto_depIdxs,
		EnumInfos:         file_mtd_proto_enumTypes,
		MessageInfos:      file_mtd_proto_msgTypes,
	}.Build()
	File_mtd_proto = out.File
	file_mtd_proto_rawDesc = nil
	file_mtd_proto_goTypes = nil
	file_mtd_proto_depIdxs = nil
}
